# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b51084a3e97ef0b9fb223bc1f23aad1d89ccc27cc45e2ed973dc6823f7165254809368d9e29540699e868872ef0f680805ced84994f029323421e3e44d5af895

test:
  secret_key_base: 0c07d312bf843550cd64ae502017984a8ab6c6d347b4fa9178088ed06883d8f558265e3e6a085315e5e591a55a4e45913909ceda646f151540915bc35d9fa0d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
